version: '3.5'
services:
    nginx:
        labels:
            traefik.enable: 'true'
            traefik.http.routers.nginx_hello_world_example.rule: 'Host(`your.example.com`)'
            traefik.http.routers.nginx_hello_world_example.tls: true
            traefik.http.routers.nginx_hello_world_example.tls.certresolver: le
