version: '3.5'
services:
    nginx:
        restart: always
        image: 'nginx:latest'
        networks:
            - traefik-local-network
            - default
        volumes:
            - './public/:/var/www/html'
            - './docker/nginx/docker/default.conf:/etc/nginx/conf.d/default.conf'
            - './docker/nginx/logs:/host/logs/nginx'
            - './docker/nginx/volumes/shared:/host/shared'

networks:
    traefik-local-network:
        external: true
